Repository NoteXCommunity/note-x, pull requests merged in 2022-10, with the labels that each got.

#63 Base Integration of Detekt Analytics tool done.
  app/src/androidTest/java/com/hadiyarajesh/notex/ExampleInstrumentedTest.kt
  app/src/main/java/com/hadiyarajesh/notex/MyApplication.kt
  app/src/main/java/com/hadiyarajesh/notex/database/converter/InstantConverter.kt
  app/src/main/java/com/hadiyarajesh/notex/database/entity/Folder.kt
  app/src/main/java/com/hadiyarajesh/notex/database/entity/Note.kt
  app/src/main/java/com/hadiyarajesh/notex/database/entity/Reminder.kt
  app/src/main/java/com/hadiyarajesh/notex/di/NetworkModule.kt
  app/src/main/java/com/hadiyarajesh/notex/di/ScopeModule.kt
  app/src/main/java/com/hadiyarajesh/notex/network/api/NoteApi.kt
  app/src/main/java/com/hadiyarajesh/notex/repository/notes/NotesRepository.kt
  app/src/main/java/com/hadiyarajesh/notex/repository/reminders/RemindersRepository.kt
  app/src/main/java/com/hadiyarajesh/notex/ui/NoteXApp.kt
  app/src/main/java/com/hadiyarajesh/notex/ui/component/AllNotesComponents.kt
  app/src/main/java/com/hadiyarajesh/notex/ui/component/Other.kt
  app/src/main/java/com/hadiyarajesh/notex/ui/component/TextComposables.kt
  app/src/main/java/com/hadiyarajesh/notex/ui/note/NotesScreen.kt
  app/src/main/java/com/hadiyarajesh/notex/ui/note/NotesViewModel.kt
  app/src/main/java/com/hadiyarajesh/notex/ui/reminders/RemindersScreen.kt
  app/src/main/java/com/hadiyarajesh/notex/ui/reminders/RemindersViewModel.kt
  app/src/main/java/com/hadiyarajesh/notex/ui/theme/Theme.kt
  app/src/main/java/com/hadiyarajesh/notex/ui/theme/Type.kt
  app/src/main/java/com/hadiyarajesh/notex/utility/PreferenceManager.kt
  app/src/test/java/com/hadiyarajesh/notex/ExampleUnitTest.kt
  build.gradle.kts
  config/detekt/detekt-baseline.xml
  config/detekt/detekt.yml
  git-hooks/pre-push
  gradlew
  scripts/pre-push
Labels: team-geet, Good to Merge Post Review.

#59 Worked on Notification and Worker
  .gitignore
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hadiyarajesh/notex/MainActivity.kt
  app/src/main/java/com/hadiyarajesh/notex/MyApplication.kt
  app/src/main/java/com/hadiyarajesh/notex/database/dao/ReminderDao.kt
  app/src/main/java/com/hadiyarajesh/notex/di/ScopeModule.kt
  app/src/main/java/com/hadiyarajesh/notex/reminder/notification/NotificationBroadCastReceiver.kt
  app/src/main/java/com/hadiyarajesh/notex/reminder/notification/NotificationDTO.kt
  app/src/main/java/com/hadiyarajesh/notex/reminder/notification/NotificationHelper.kt
  app/src/main/java/com/hadiyarajesh/notex/reminder/worker/ReminderWorkManager.kt
  app/src/main/java/com/hadiyarajesh/notex/reminder/worker/ReminderWorker.kt
  app/src/main/java/com/hadiyarajesh/notex/repository/reminders/RemindersRepository.kt
  app/src/main/java/com/hadiyarajesh/notex/ui/reminders/RemindersScreen.kt
  app/src/main/java/com/hadiyarajesh/notex/ui/reminders/RemindersViewModel.kt
  app/src/main/res/values/strings.xml
Labels: team-geet

#49 Simba/feature/note folder screen UI
  .idea/misc.xml
  app/src/main/java/com/hadiyarajesh/notex/ui/folders/NoteFolderScreen.kt
  app/src/main/java/com/hadiyarajesh/notex/ui/folders/NoteFolderViewModel.kt
  app/src/main/java/com/hadiyarajesh/notex/ui/navigation/Screens.kt
  app/src/main/res/drawable/ic_add_circle_outline.xml
  app/src/main/res/drawable/ic_folder_filled.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values/strings.xml
Labels: team-rajesh
